#!/bin/sh

echo "valid variable names:"
echo "SKILL\nSKILL1\n_SKILL\n"
echo "starting with letter case or underscore is fine"

echo "invalid variable names:"
echo "3SKILL\nA-SKILL\nE@MAIL\n"
echo "number cannot be the first letter and no hypen or other special character other than _ (underscore) in any place"
echo ""
echo "By the convention, use CAPITAL(upper case) for variable name"
echo ""
echo "in this exampe where it says:"
echo "echo \"my name is \${NAME}\" #important to use \${} to indicate variable_name"
echo "Because this allows the script executor to find the correct varaible"
echo "for exmaple:"
echo "echo \"\${NAME}ing\" vs echo \"\$NAMEing\""
